export interface EdgeVoiceSnapshotEntry {
  id: string;
  name: string;
  description?: string;
}

/**
 * 内置音色快照：中文（含繁体、方言）与英语音色，取自微软 Edge 朗读接口的公开音色列表。
 * 仅作为无外网 / 尚未刷新时的兜底；管理员刷新后以运行时配置中的实时清单为准。
 * 本文件由脚本生成，请勿手工编辑。
 */
export const EDGE_BUILTIN_VOICE_OPTIONS: readonly EdgeVoiceSnapshotEntry[] = [
  { id: "en-AU-NatashaNeural", name: "Natasha", description: "English (Australia) · 女" },
  { id: "en-AU-WilliamMultilingualNeural", name: "William Multilingual", description: "English (Australia) · 男" },
  { id: "en-CA-ClaraNeural", name: "Clara", description: "English (Canada) · 女" },
  { id: "en-CA-LiamNeural", name: "Liam", description: "English (Canada) · 男" },
  { id: "en-GB-LibbyNeural", name: "Libby", description: "English (United Kingdom) · 女" },
  { id: "en-GB-MaisieNeural", name: "Maisie", description: "English (United Kingdom) · 女" },
  { id: "en-GB-RyanNeural", name: "Ryan", description: "English (United Kingdom) · 男" },
  { id: "en-GB-SoniaNeural", name: "Sonia", description: "English (United Kingdom) · 女" },
  { id: "en-GB-ThomasNeural", name: "Thomas", description: "English (United Kingdom) · 男" },
  { id: "en-HK-SamNeural", name: "Sam", description: "English (Hong Kong SAR) · 男" },
  { id: "en-HK-YanNeural", name: "Yan", description: "English (Hong Kong SAR) · 女" },
  { id: "en-IE-ConnorNeural", name: "Connor", description: "English (Ireland) · 男" },
  { id: "en-IE-EmilyNeural", name: "Emily", description: "English (Ireland) · 女" },
  { id: "en-IN-NeerjaExpressiveNeural", name: "Neerja", description: "English (India) · 女" },
  { id: "en-IN-NeerjaNeural", name: "Neerja", description: "English (India) · 女" },
  { id: "en-IN-PrabhatNeural", name: "Prabhat", description: "English (India) · 男" },
  { id: "en-KE-AsiliaNeural", name: "Asilia", description: "English (Kenya) · 女" },
  { id: "en-KE-ChilembaNeural", name: "Chilemba", description: "English (Kenya) · 男" },
  { id: "en-NG-AbeoNeural", name: "Abeo", description: "English (Nigeria) · 男" },
  { id: "en-NG-EzinneNeural", name: "Ezinne", description: "English (Nigeria) · 女" },
  { id: "en-NZ-MitchellNeural", name: "Mitchell", description: "English (New Zealand) · 男" },
  { id: "en-NZ-MollyNeural", name: "Molly", description: "English (New Zealand) · 女" },
  { id: "en-PH-JamesNeural", name: "James", description: "English (Philippines) · 男" },
  { id: "en-PH-RosaNeural", name: "Rosa", description: "English (Philippines) · 女" },
  { id: "en-SG-LunaNeural", name: "Luna", description: "English (Singapore) · 女" },
  { id: "en-SG-WayneNeural", name: "Wayne", description: "English (Singapore) · 男" },
  { id: "en-TZ-ElimuNeural", name: "Elimu", description: "English (Tanzania) · 男" },
  { id: "en-TZ-ImaniNeural", name: "Imani", description: "English (Tanzania) · 女" },
  { id: "en-US-AnaNeural", name: "Ana", description: "English (United States) · 女" },
  { id: "en-US-AndrewMultilingualNeural", name: "Andrew Multilingual", description: "English (United States) · 男" },
  { id: "en-US-AndrewNeural", name: "Andrew", description: "English (United States) · 男" },
  { id: "en-US-AriaNeural", name: "Aria", description: "English (United States) · 女" },
  { id: "en-US-AvaMultilingualNeural", name: "Ava Multilingual", description: "English (United States) · 女" },
  { id: "en-US-AvaNeural", name: "Ava", description: "English (United States) · 女" },
  { id: "en-US-BrianMultilingualNeural", name: "Brian Multilingual", description: "English (United States) · 男" },
  { id: "en-US-BrianNeural", name: "Brian", description: "English (United States) · 男" },
  { id: "en-US-ChristopherNeural", name: "Christopher", description: "English (United States) · 男" },
  { id: "en-US-EmmaMultilingualNeural", name: "Emma Multilingual", description: "English (United States) · 女" },
  { id: "en-US-EmmaNeural", name: "Emma", description: "English (United States) · 女" },
  { id: "en-US-EricNeural", name: "Eric", description: "English (United States) · 男" },
  { id: "en-US-GuyNeural", name: "Guy", description: "English (United States) · 男" },
  { id: "en-US-JennyNeural", name: "Jenny", description: "English (United States) · 女" },
  { id: "en-US-MichelleNeural", name: "Michelle", description: "English (United States) · 女" },
  { id: "en-US-RogerNeural", name: "Roger", description: "English (United States) · 男" },
  { id: "en-US-SteffanNeural", name: "Steffan", description: "English (United States) · 男" },
  { id: "en-ZA-LeahNeural", name: "Leah", description: "English (South Africa) · 女" },
  { id: "en-ZA-LukeNeural", name: "Luke", description: "English (South Africa) · 男" },
  { id: "zh-CN-XiaoxiaoNeural", name: "晓晓", description: "Chinese (Mandarin, Simplified) · 女" },
  { id: "zh-CN-XiaoyiNeural", name: "晓伊", description: "Chinese (Mandarin, Simplified) · 女" },
  { id: "zh-CN-YunjianNeural", name: "云健", description: "Chinese (Mandarin, Simplified) · 男" },
  { id: "zh-CN-YunxiNeural", name: "云希", description: "Chinese (Mandarin, Simplified) · 男" },
  { id: "zh-CN-YunxiaNeural", name: "云夏", description: "Chinese (Mandarin, Simplified) · 男" },
  { id: "zh-CN-YunyangNeural", name: "云扬", description: "Chinese (Mandarin, Simplified) · 男" },
  { id: "zh-CN-liaoning-XiaobeiNeural", name: "Xiaobei", description: "Chinese (Northeastern Mandarin, Simplified) · 女" },
  { id: "zh-CN-shaanxi-XiaoniNeural", name: "Xiaoni", description: "Chinese (Zhongyuan Mandarin Shaanxi, Simplified) · 女" },
  { id: "zh-HK-HiuGaaiNeural", name: "HiuGaai", description: "Chinese (Cantonese, Traditional) · 女" },
  { id: "zh-HK-HiuMaanNeural", name: "HiuMaan", description: "Chinese (Cantonese, Traditional) · 女" },
  { id: "zh-HK-WanLungNeural", name: "WanLung", description: "Chinese (Cantonese, Traditional) · 男" },
  { id: "zh-TW-HsiaoChenNeural", name: "HsiaoChen", description: "Chinese (Taiwanese Mandarin, Traditional) · 女" },
  { id: "zh-TW-HsiaoYuNeural", name: "HsiaoYu", description: "Chinese (Taiwanese Mandarin, Traditional) · 女" },
  { id: "zh-TW-YunJheNeural", name: "YunJhe", description: "Chinese (Taiwanese Mandarin, Traditional) · 男" },
];
